os: linux
dist: trusty
sudo: required
language: c

addons:
  apt:
    packages:
    - lftp
    - lib32z1
    - lib32stdc++6
    - rsync

env:
  - VERSION=1.8
  - VERSION=1.9
  - VERSION=1.10

before_script:
  - 'if [[ $TRAVIS_PULL_REQUEST != "false" || $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH != "master" && $TRAVIS_BRANCH != "stable" ]]; then bash -c ci/test.sh $VERSION "dev"; fi'
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == "stable" ]]; then bash -c ci/build.sh $VERSION "dev" $FTP_HOST $FTP_USER $FTP_PASS $TRAVIS_JOB_ID; fi'

script:
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == "stable" ]]; then bash -c ci/upload.sh $VERSION "dev" $FTP_HOST $FTP_USER $FTP_PASS $TRAVIS_JOB_ID; fi'

notifications:
  email: false
  webhooks:
    urls:
      - https://csgottt.com/discord-travis-ci.php
    on_success: always
    on_failure: always
    on_cancel: always
    on_error: always
