name: Compile with SourceMod

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        sm_version: ['1.9', '1.10', '1.11']

    steps:
    - uses: actions/checkout@v1
    - name: Download sourcemod
      run: |
        wget "http://www.sourcemod.net/latest.php?version=${{ matrix.sm_version }}&os=linux" -O sourcemod.tar.gz
        tar -xzf sourcemod.tar.gz --exclude='addons/sourcemod/translations'
    - name: Give spcomp the required permissions
      run: chmod +x addons/sourcemod/scripting/spcomp
    - name: Compiling of all TTT related plugins
      run: |
        for file in addons/sourcemod/scripting/ttt/*.sp
        do
          echo -e "\nCompiling $file..." 
          addons/sourcemod/scripting/spcomp -w234 -O2 -v2 $file
        done
        
    - name: Compile 3rd-party-plugins
      run: |
        echo -e "\nCompiling addons/sourcemod/scripting/block_messages.sp..."
        addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 addons/sourcemod/scripting/block_messages.sp
        echo -e "\nCompiling addons/sourcemod/scripting/discord_api.sp..."
        addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 addons/sourcemod/scripting/discord_api.sp
        echo -e "Compiling addons/sourcemod/scripting/ghostdm.sp..."
        addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 addons/sourcemod/scripting/ghostdm.sp
        echo -e "\nCompiling addons/sourcemod/scripting/no_weapon_fix.sp..."
        addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 addons/sourcemod/scripting/no_weapon_fix.sp
        echo -e "\nCompiling addons/sourcemod/scripting/tripmines.sp..."
        addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 addons/sourcemod/scripting/tripmines.sp
        echo -e "\nCompiling addons/sourcemod/scripting/turret_core.sp..."
        addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 addons/sourcemod/scripting/turret_core.sp

    - name: Remove plugins folder and create new ones
      run: |
        if [ -d "addons/sourcemod/plugins" ]; then
          rm -r addons/sourcemod/plugins
        fi
        mkdir addons/sourcemod/plugins
        mkdir addons/sourcemod/plugins/disabled
        mkdir addons/sourcemod/plugins/ttt
        
    - name: Move all TTT smx files into the plugins folder
      run: |
        for file in ttt*.smx
        do
          mv $file addons/sourcemod/plugins/ttt
        done
      
    - name: Move 3rd-party-plugins into the plugins folder
      run: |
        for file in *.smx
        do
          mv $file addons/sourcemod/plugins
        done
        
    - name: Remove build folder and create new one
      run: |
        if [ -d "build" ]; then
          rm -r build
        fi
        mkdir -p build/${{ matrix.sm_version }}/
      
    - name: Move addons, materials, models and sound folder
      run: mv addons materials models sound build/${{ matrix.sm_version }}/
    
    - name: Remove sourcemod folders
      run: |
        rm -r build/${{ matrix.sm_version }}/addons/metamod
        rm -r build/${{ matrix.sm_version }}/addons/sourcemod/bin
        rm -r build/${{ matrix.sm_version }}/addons/sourcemod/configs/geoip
        rm -r build/${{ matrix.sm_version }}/addons/sourcemod/configs/sql-init-scripts
        rm -r build/${{ matrix.sm_version }}/addons/sourcemod/configs/*.txt
        rm -r build/${{ matrix.sm_version }}/addons/sourcemod/configs/*.ini
        rm -r build/${{ matrix.sm_version }}/addons/sourcemod/configs/*.cfg
        rm -r build/${{ matrix.sm_version }}/addons/sourcemod/data
        rm -r build/${{ matrix.sm_version }}/addons/sourcemod/extensions
        rm -r build/${{ matrix.sm_version }}/addons/sourcemod/gamedata
        rm -r build/${{ matrix.sm_version }}/addons/sourcemod/scripting
        rm build/${{ matrix.sm_version }}/addons/sourcemod/*.txt
        
    - name: Add LICENSE, CREDITS.md, CVARS.txt and adminmenu_custom.txt to build package
      run: cp LICENSE CREDITS.md CVARS.txt adminmenu_custom.txt build/${{ matrix.sm_version }}/
    
    - name: Download steamworks and move into the build package
      run: |
        wget http://users.alliedmods.net/~kyles/builds/SteamWorks/SteamWorks-git131-linux.tar.gz -O steamworks_linux.tar.gz
        tar xfv steamworks_linux.tar.gz
        wget http://users.alliedmods.net/~kyles/builds/SteamWorks/SteamWorks-git131-windows.zip -O steamworks_windows.zip
        unzip -o steamworks_windows.zip
        mkdir -p build/${{ matrix.sm_version }}/addons/sourcemod/extensions/
        cp addons/sourcemod/extensions/SteamWorks.ext.so build/${{ matrix.sm_version }}/addons/sourcemod/extensions/
        cp addons/sourcemod/extensions/SteamWorks.ext.dll build/${{ matrix.sm_version }}/addons/sourcemod/extensions/
      
    - name: Clean up root directory
      run: |
        rm sourcemod.tar.gz
        rm steamworks_linux.tar.gz
        rm steamworks_windows.zip
      
    - uses: actions/upload-artifact@master
      with:
        name: ttt.${{ matrix.sm_version }}.${{ github.sha }}-zip
        path: build/${{ matrix.sm_version }}/
