name: Compile with SourceMod

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.10", "1.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo ::set-env name=SOURCEMOD_PATH::$SOURCEMOD_PATH
          echo ::set-env name=SCRIPTS_PATH::$SOURCEMOD_PATH/scripting

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}
      
      - name: Generate colorlib.inc
        run: python3 ./color_gen.py -r --config "./ttt_colors.yaml" "../addons/sourcemod/scripting/include/colorlib_map.inc"
        working-directory: ./tools

      - name: Compile TTT
        run: |
          for file in *.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i $SCRIPTS_PATH/include $file
          done
        working-directory: ${{ env.SCRIPTS_PATH }}/ttt

      - name: Compile 3rd party plugins
        run: |
          for plugin in "block_messages" "customkeyvalues" "discord_api" "no_weapon_fix" "turret_core"
          do
            echo -e "\nCompiling $plugin.sp..."
            spcomp -E -w234 -O2 -v2 -i $SCRIPTS_PATH/include $plugin.sp
          done
        working-directory: ${{ env.SCRIPTS_PATH }}/
