name: Compile with SourceMod 1.10

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download sourcemod
      run: |
        wget "http://www.sourcemod.net/latest.php?version=1.10&os=linux" -O sourcemod.tar.gz
        tar -xzf sourcemod.tar.gz
    - name: Give spcomp the required permissions
      run: chmod +x addons/sourcemod/scripting/spcomp
    - name: Compiling of all TTT related plugins
      run: |
        for file in addons/sourcemod/scripting/ttt/*.sp
        do
          echo -e "\nCompiling $file..." 
          addons/sourcemod/scripting/spcomp -w234 -O2 -v2 $file
        done
        
    - name: Compile 3rd-party-plugins
      run: |
        echo -e "\nCompiling addons/sourcemod/scripting/block_messages.sp..."
        addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 addons/sourcemod/scripting/block_messages.sp
        echo -e "Compiling addons/sourcemod/scripting/ghostdm.sp..."
        addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 addons/sourcemod/scripting/ghostdm.sp
        echo -e "\nCompiling addons/sourcemod/scripting/no_weapon_fix.sp..."
        addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 addons/sourcemod/scripting/no_weapon_fix.sp
        echo -e "\nCompiling addons/sourcemod/scripting/tripmines.sp..."
        addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 addons/sourcemod/scripting/tripmines.sp
        echo -e "\nCompiling addons/sourcemod/scripting/turret_core.sp..."
        addons/sourcemod/scripting/spcomp -E -w234 -O2 -v2 addons/sourcemod/scripting/turret_core.sp
      
